# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-16 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0002_auto_20160106_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnsdevice',
            name='registration_id',
            field=models.CharField(max_length=200, verbose_name='Registration ID'),
        ),
    ]
